job_titles = [
    "Frontend Developer",
    "Backend Developer",
    "Fullstack Developer",
    "Software Engineer",
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "React Developer",
    "Angular Developer",
    "Vue Developer",
    "Svelte Developer",
    "Node.js Developer",
    "Java Developer",
    "Python Developer",
    "C# Developer",
    "C++ Developer",
    "Go Developer",
    "Rust Developer",
    "Kotlin Developer",
    "Swift Developer",
    "PHP Developer",
    "Ruby Developer",
    "Django Developer",
    "Flask Developer",
    "Spring Boot Developer",
    "Laravel Developer",
    "Rails Developer",
    "DevOps Engineer",
    "Cloud Engineer",
    "AWS Engineer",
    "Azure Engineer",
    "GCP Engineer",
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Deep Learning Engineer",
    "AI Engineer",
    "MLOps Engineer",
    "Business Intelligence Developer",
    "Database Administrator",
    "Big Data Engineer",
    "ETL Developer",
    "Backend API Developer",
    "Frontend UI/UX Engineer",
    "Software Architect",
    "System Architect",
    "Embedded Software Engineer",
    "Game Developer",
    "Unity Developer",
    "Unreal Engine Developer",
    "Blockchain Developer",
    "Cybersecurity Engineer",
    "QA Engineer",
    "Test Automation Engineer",
    "SDET",
    "Site Reliability Engineer",
    "Release Engineer",
    "Fullstack Web Developer",
    "Cloud Solutions Architect",
    "Product Engineer",
    "Technical Lead",
    "Engineering Manager",
    "Software Development Manager"
]